# 
# Available types:  
#  stream:  just play the stream
#  mp3_loop_random_start:  play one audio file, seek to a random position, loop forever
#  mp3_dir_random_start_then_in_order:  choose one item randomly from the listed directory.  Play the item from the start, then continue playing items from the directory in order, looping to the beginning of the directory once the end is reached.
#  
banks:
  0:
    name: "Jazz"
    stations:
      0:
        name: "WWOZ New Orleans"
        type: stream
        url: "http://wwoz-sc.streamguys.com/wwoz-hi.mp3"
      1:
        name: "WBGO"
        type: stream
        url: "https://ais-sa8.cdnstream1.com/3629_64.aac"
      2:
        name: "WDCB"
        type: stream
        url: "https://wdcb-ice.streamguys1.com/mobile-AAC"
      3:
        name: "KMHD"
        type: stream
        url: "https://ais-sa3.cdnstream1.com/2442_128.aac/playlist.m3u8"
      4:
        name: "KCSM"
        type: stream
        url: "https://ice7.securenetsystems.net/KCSM2"
      5:
        name: "WPFW"
        type: stream
        url: "https://streams.pacifica.org:9000/wpfw_128"
      6:
        name: "KUVO"
        type: stream
        url: "https://kuvo.streamguys1.com/kuvo-aac-128"
      7:
        name: "CJRT 91.1 Jazz FM"
        type: stream
        url: "https://hil-streamb1-ais-relay1.streamb.live/SB00009/playlist.m3u8"
      8:
        name: "Jazz 88.3 San Diego"
        type: stream
        url: "https://ksds-ice.streamguys1.com/ksds.mp3"
      9:
        name: "Czech Jazz"
        type: stream
        url: "https://rozhlas.stream/jazz_high.aac"
  1:
    name: "Classical"
    stations:
      0:
        name: "WFMT"
        type: stream
        url: "https://wfmt.streamguys1.com/main-mp3"
      1:
        name: "Classic FM - London"
        type: stream
        url: "https://media-ice.musicradio.com/ClassicFMMP3"
      2:
        name: "Radio Classique - France"
        type: stream
        url: "https://radioclassique.ice.infomaniak.ch/radioclassique-high.mp3?.mp3"
      3:
        name: "Classic KING FM - Seattle"
        type: stream
        url: "https://classicalking.streamguys1.com/king-fm-aac-128k"
      4:
        name: "Klassik 1 - Berlin"
        type: stream
        url: "https://icepool.silvacast.com/KLASSIK1.mp3"
      5:
        name: "WQXR"
        type: stream
        url: "https://stream.wqxr.org/wqxr-web"
      6:
        name: "KQAC"
        type: stream
        url: "https://allclassical.streamguys1.com/ac128kmp3"
        # PLAYS AD FIRST
      7:
        name: "WDAV - Davidson College NC"
        type: stream
        url: "https://audio-mp3.ibiblio.org/wdav-112k"
      8:
        name: "Radio Swiss Classical"
        type: stream
        url: "https://stream.srg-ssr.ch/srgssr/rsc_de/aac/96"
      9:
        name: "KVOD - Denver"
        type: stream
        url: "https://stream1.cprnetwork.org/cpr2_lo"
        # PLAYS AD FIRST
  2:
    name: "Around the US"
    stations:
      0:
        name: "WFMU 91.1 Hudsdon Valley"
        type: stream
        url: "https://stream0.wfmu.org/freeform-128k.mp3"
      1:
        name: "WPKN Bridgeport, Connecticut 89.5"
        type: stream
        url: "https://ice25.securenetsystems.net/WPKN"
      2:
        name: "KEXP Seattle 90.3 FM"
        type: stream
        url: "https://kexp-mp3-128.streamguys1.com/kexp128.mp3"        
      3:
        name: "KABF Little Rock"
        type: stream
        url: "https://cast.acornradio.org/kabf"
      4:
        name: "SoCal Sound 88.5 FM"
        type: stream
        url: "https://www.streamvortex.com:8444/s/12200/"
      5:
        name: "Hot 97 NYC"
        type: stream
        url: "https://27253.live.streamtheworld.com/WQHTFMAAC.aac"
        # PLAYS AD FIRST
      6:
        name: "Iowa Public Radio"
        type: stream
        url: "https://studioone-stream.iowapublicradio.org/StudioOne.mp3"
      7:
        name: "WDVX 89.9 Knoxville"
        type: stream
        url: "https://wdvx.streamguys1.com/live"
        # QUIET
      8:
        name: "WMOT 89.5 Middle Tennessee"
        type: stream
        url: "https://26443.live.streamtheworld.com/WMOTFM.mp3"
      9:
        name: "WFUV Fordham University"
        type: stream
        url: "https://onair.wfuv.org/onair-aacplus"
        # PLAYS AD FIRST
  3:
    name: "Around the world 1"
    stations:
      0:
        name: "La Kalle 96.9"
        type: stream
        url: "https://27383.live.streamtheworld.com/LA_KALLE.mp3"
      1:
        name: "Los 40 Principales Mexico"
        type: stream
        url: "https://26733.live.streamtheworld.com/LOS40_MEXICO.mp3"
      2:
        name: "Alpha Boys School Radio - Jamaica"
        type: stream
        url: "https://alphaboys-live.streamguys1.com/alphaboys.aac"
      3:
        name: "Ashiya - Japan"
        type: stream
        url: "https://s3.radio.co/sc8d895604/listen"
      4:
        name: "WREP Live - Tokyo"
        type: stream
        url: "https://c13.radioboss.fm:8200/stream"
      5:
        name: "Radio Eigekai"
        type: stream
        url: "http://stream.radiojar.com/66zgtscuc1duv?1768412014"
      6:
        name: "Red Dirt Radio - Australia"
        type: stream
        url: "https://az1.syd2.hostyourservices.au:8010/magic876"
      7:
        name: "Punk Radio Underground Poland"
        type: stream
        url: "https://s1.slotex.pl:7604/stream/1/"
      8:
        name: "fbi Sydney"
        type: stream
        url: "https://streamer.fbiradio.com/stream"
      9:
        name: "triple j Australia"
        type: stream
        url: "https://streaming.abc-cdn.net.au/audio/hls/triplejnsw.m3u8"
  4:
    name: "Around the world 2"
    stations:
      0:
        name: "FIP France"
        type: stream
        url: "https://stream.radiofrance.fr/fip/fip_hifi.m3u8"
      1:
        name: "Radio Nova France"
        type: stream
        url: "https://novazz.ice.infomaniak.ch/novazz-128.mp3"
      2:
        name: "PHEVER Dublin"
        type: stream
        url: "https://uk1.internet-radio.com/proxy/phever?mp=/stream"
      3:
        name: "Highland Radio Letterkenny Ireland"
        type: stream
        url: "https://29103.live.streamtheworld.com/HIGHLAND_RADIO.mp3"
      4:
        name: "RTE Lyric Dublin"
        type: stream
        url: "https://www.rte.ie/manifests/lyric.m3u8"
      5:
        name: "GPM Radio Russia"
        type: stream
        url: "https://srv01.gpmradio.ru/stream/pro/aac/64/41"
      6:
        name: "Transilvania"
        type: stream
        url: "https://s2.radio.co/sce9d4eadd/listen"
      7:
        name: "Nova Brasil FM"
        type: stream
        url: "https://27403.live.streamtheworld.com/NOVABRASIL_SSAAAC.aac"
      8:
        name: "Radio Rebelde Havana"
        type: stream
        url: "https://icecast.teveo.cu/zrXXWK9F"
      9:
        name: "Yabiladi Casablanca Morocco"
        type: stream
        url: "https://radio.yabiladi.com:9002/;stream.mp3"
  5:
    name: "BBC"
    stations:
      0:
        name: "BBC Radio One"
        type: stream
        url: "http://as-hls-ww-live.akamaized.net/pool_01505109/live/ww/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d128000.norewind.m3u8"
      1:
        name: "BBC Radio Two"
        type: stream
        url: "http://as-hls-ww-live.akamaized.net/pool_74208725/live/ww/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio%3d128000.norewind.m3u8"
      2:
        name: "BBC Radio Three"
        type: stream
        url: "http://as-hls-ww-live.akamaized.net/pool_23461179/live/ww/bbc_radio_three/bbc_radio_three.isml/bbc_radio_three-audio%3d128000.norewind.m3u8"
      3:
        name: "BBC Radio Four"
        type: stream
        url: "http://as-hls-ww-live.akamaized.net/pool_55057080/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d128000.norewind.m3u8"
      4:
        name: "BBC Radio Five Live"
        type: stream
        url: "http://as-hls-ww-live.akamaized.net/pool_89021708/live/ww/bbc_radio_five_live/bbc_radio_five_live.isml/bbc_radio_five_live-audio%3d128000.norewind.m3u8"
      5:
        name: "BBC Radio Six Music"
        type: stream
        url: "http://as-hls-ww-live.akamaized.net/pool_81827798/live/ww/bbc_6music/bbc_6music.isml/bbc_6music-audio%3d128000.norewind.m3u8"
      6:
        name: "BBC Radio Scotland"
        type: stream
        url: "http://as-hls-ww-live.akamaized.net/pool_43322914/live/ww/bbc_radio_scotland_fm/bbc_radio_scotland_fm.isml/bbc_radio_scotland_fm-audio%3d128000.norewind.m3u8"
      7:
        name: "BBC Radio Wales"
        type: stream
        url: "http://as-hls-ww-live.akamaized.net/pool_97517794/live/ww/bbc_radio_wales_fm/bbc_radio_wales_fm.isml/bbc_radio_wales_fm-audio%3d128000.norewind.m3u8"
      8:
        name: "BBC Radio World Service"
        type: stream
        url: "http://as-hls-ww-live.akamaized.net/pool_87948813/live/ww/bbc_world_service/bbc_world_service.isml/bbc_world_service-audio%3d128000.norewind.m3u8"
      9:
        name: "BBC Radio Three Unwind"
        type: stream
        url: "http://as-hls-ww-live.akamaized.net/pool_30624046/live/ww/bbc_radio_three_unwind/bbc_radio_three_unwind.isml/bbc_radio_three_unwind-audio%3d128000.norewind.m3u8"
  6:
    name: "College Radio"
    stations:
      0:
        name: "WKCR Columbia"
        type: stream
        url: "https://wkcr.streamguys1.com/live"
      1:
        name: "WNYU"
        type: stream
        url: "http://cinema.acs.its.nyu.edu:8000/wnyu128.mp3"
      2:
        name: "WCBN U of Michigan"
        type: stream
        url: "https://floyd.wcbn.org:8443/wcbn-hd.mp3"
      3:
        name: "KVCU CU Boulder"
        type: stream
        url: "https://kvcu.streamguys1.com/live"
      4:
        name: "WKNC NC State Raleigh"
        type: stream
        url: "https://das-edge14-live365-dal02.cdnstream.com/a45877"
      5:
        name: "KALX UC Berkeley"
        type: stream
        url: "https://stream.kalx.berkeley.edu:8443/kalx-128.mp3"
      6:
        name: "KCRW Santa Monica College"
        type: stream
        url: "https://streams.kcrw.com/kcrw_mp3"
      7:
        name: "KUAF U of A Fayetteville"
        type: stream
        url: "https://war.streamguys1.com:7031/kuaf1"
      8:
        name: "WIDR FM Western Michigan University in Kalamazoo"
        type: stream
        url: "https://widrfm.net/stream"
      9:
        name: "KSPC Claremont Colleges"
        type: stream
        url: "https://kspc.radioca.st/stream"
  7:
    name: "Ambient"
    stations:
      0:
        name: "Mission Control - Soma FM"
        type: stream
        url: "https://ice5.somafm.com/missioncontrol-128-aac"
      1:
        name: "Drone Zone - Soma FM"
        type: stream
        url: "https://ice5.somafm.com/dronezone-128-aac"
      2:
        name: "Space Station Soma FM"
        type: stream
        url: "https://ice5.somafm.com/spacestation-128-aac"
      3:
        name: "DEF CON Radio Soma FM"
        type: stream
        url: "https://ice5.somafm.com/defcon-128-aac"
      4:
        name: "Dark Zone Soma FM"
        type: stream
        url: "https://ice5.somafm.com/darkzone-128-aac"
      5:
        name: "Vaporwaves Soma FM"
        type: stream
        url: "https://ice5.somafm.com/vaporwaves-128-aac"
      6:
        name: "Soma FM Specials"
        type: stream
        url: "https://ice5.somafm.com/specials-128-aac"
      7:
        name: "9128.live"
        type: stream
        url: "https://streams.radio.co/s0aa1e6f4a/listen"
      8:
        name: "Moon Phase Radio Hertford UK"
        type: stream
        url: "https://cp12.serverse.com/proxy/moonphase/stream"
      9:
        name: "Morong Community Radio Philippines"
        type: stream
        url: "https://broadcast.shoutcheap.com/proxy/morong/stream" 
  8:
    name: "Grand Theft Auto"
    stations:
      0:
        name: "FlyLo FM"
        type: mp3_loop_random_start
        file: "GTA/FlyLo FM - GTA V.mp3"
      1:
        name: "Fusion FM"
        type: mp3_loop_random_start
        file: "GTA/Fusion FM - GTA IV.mp3"
      2:
        name: "Los Santos Rock Radio"
        type: mp3_loop_random_start
        file: "GTA/Los Santos Rock Radio - GTA V.mp3"
      3:
        name: "MSX FM"
        type: mp3_loop_random_start
        file: "GTA/MSX FM - GTA III.mp3"
      4:
        name: "Jazz Nation Radio"
        type: mp3_loop_random_start
        file: "GTA/Jazz Nation Radio - GTA IV.mp3"
      5:
        name: "K-DST"
        type: mp3_loop_random_start
        file: "GTA/K-DST - GTA San Andreas.mp3"
      6:
        name: "K Rose"
        type: mp3_loop_random_start
        file: "GTA/K Rose - GTA San Andreas.mp3"
      7:
        name: "Blue Ark Radio"
        type: mp3_loop_random_start
        file: "GTA/The Blue Ark - GTA V.mp3"
      8:
        name: "K-JAH Radio"
        type: mp3_loop_random_start
        file: "GTA/K-JAH - GTA III.mp3"
      9:
        name: "Non-Stop Pop"
        type: mp3_loop_random_start
        file: "GTA/Non Stop Pop FM - GTA V.mp3"
  9:
    name: "Offline Recordings"
    stations:
      0:
        name: "Theme Time Radio with Bob Dylan"
        type: mp3_dir_random_start_then_in_order
        dir: "shows/BobDylan"
      1:
        name: "Iggy Pop"
        type: mp3_dir_random_start_then_in_order
        dir: "shows/IggyPop"
      2:
        name: "Jarvis Cocker"
        type: mp3_dir_random_start_then_in_order
        dir: "shows/JarvisCocker"    
      3:
        name: "Joe Strummer"
        type: mp3_dir_random_start_then_in_order
        dir: "shows/JoeStrummer"    
      4:
        name: "John Peel"
        type: mp3_dir_random_start_then_in_order
        dir: "shows/JohnPeel"    
      5:
        name: "Marian McPartlan"
        type: mp3_dir_random_start_then_in_order
        dir: "shows/MarianMcPartland"    
      6:
        name: "Paul McCartney"
        type: mp3_dir_random_start_then_in_order
        dir: "shows/PaulMcCartney"    
      7:
        name: "Henry Rollins"
        type: mp3_dir_random_start_then_in_order
        dir: "shows/HenryRollins"    
      8:
        name: "Muji BGM 1980-2000"
        type: mp3_loop_random_start
        file: "Ambient/Muji BGM 1980-2000.mp3"    
      9:
        name: "Alice Cooper"
        type: mp3_dir_random_start_then_in_order
        dir: "shows/AliceCooper"    

